"""
Presentation-neutral download progress sink.

The core (downloader + service) reports progress by calling these methods; it
knows nothing about how they are rendered. The base class is a usable no-op
("null object"), so callers never need to check for None. Frontends subclass it:
`ui.RichDownloadObserver` renders to the terminal; a future GUI would render to
widgets / push over a socket.

Events are keyed by chapter title. `num` is the chapter's 1-based position in
the current selection; `start()` provides the total up front.
"""

from __future__ import annotations


class DownloadObserver:
    """No-op base. Override the methods you care about."""

    # ── lifecycle ────────────────────────────────────────────────────────────
    def start(self, total_chapters: int) -> None: ...
    def stop(self) -> None: ...

    # ── fetch (URL collection) panel ─────────────────────────────────────────
    def fetch_skipped(self, key: str, num: int) -> None: ...
    def fetch_started(self, key: str, num: int) -> None: ...
    def fetch_failed(self, key: str, num: int) -> None: ...
    def fetch_retry(self, key: str, num: int, attempt: int, max_attempts: int) -> None: ...

    # ── per-chapter download + PDF build progress ────────────────────────────
    def download_started(self, key: str, total_images: int) -> None: ...
    def image_downloaded(self, key: str) -> None: ...
    def build_started(self, key: str, total_pages: int) -> None: ...
    def page_built(self, key: str) -> None: ...
    def chapter_saved(self, key: str, filename: str, pages: int, spreads: int) -> None: ...
    def chapter_failed(self, key: str, num: int) -> None: ...

    # ── freeform info (e.g. an internal skip) ────────────────────────────────
    def message(self, text: str) -> None: ...
